### ISSUE TITLE
Review #1 - Algunas secciones se rompen.

### ISSUE THREAD

**Issue by FacundoEG** [PabloMartinsDeMaltoz/Desafio-M4#1]
Hola Pablo! como estas? primero que todo te quiero felicitar por haber enviado el desafío del modulo 4!

Te comento que estuve revisando el desafío y note un pequeño detalle dentro de la .section-presentación en la homepage.

![image](https://user-images.githubusercontent.com/79592789/145219895-0920e78e-fb0d-4d23-8d5d-026bcb02df14.png)

Fijate que entre aproximadamente los 1050px de ancho hasta el breakpoint a mobile, esta sección se rompe un poco y algunos elementos quedan por fuera del viewport.

Podría sugerirte para no realizar tantos cambios, que muevas dicho breakpoint a desktop recien en esta resolución asi te aseguras que esa parte de la page se vea siempre bien. 

Si no se me ocurre un media query para que vayas controlando que pasa entre ese nivel de ancho (osea entre el breakpoint y los 1050px) donde podrías sacarle el gap o bajarle el ancho al elemento que contiene el parrafo.

En la page de "porfolio" y "servicos" tambien sucede algo similar con los contenedores que tienen templates:

![image](https://user-images.githubusercontent.com/79592789/145222858-cf250585-113d-4503-ad9a-f95d6ea94c5b.png)

Fijate que los elementos de servicios__section no quedan bien acomodados hasta recien poder alcanzar los 1100px de ancho para arriba.

Ahi sería algo similar, podrías subirle el breakpoint o revisar los margenes de dicho contenedor.

Por mi parte te podría sugerir que estaría bueno que consideres usar display:flex junto a la propiedad flex:wrap que te ayudaria a solucionar el tema ya que acomodaría algunos elementos hacia abajo cuando no se puedan contener dentro del ancho. 

![image](https://user-images.githubusercontent.com/79592789/145222155-29f4a7f9-167e-45b7-82c2-a45fab4c6041.png)

A modo de arquitectura te aconsejaría tambien que no le pongas el mismo titulo a ambas paginas (osea poniendole "portfolio/servicios") como titulo principal, ya que no se termina de diferenciar bien y puede ser confuso para mostrar el contenido.

Sacando esos detalles la verdad que la pagina esta exelente! el diseño se ve super solido y las otras secciones responden muy bien! sumandole a que maneja una buena responsividad mobile.

Asi que de mi parte te recomendaría que revises el tema de esos contenedores y realices algunos cambios si? 

Te mando saludos y cualquier duda que tengas podes preguntarme por aca o mismo en el canal del desafío!

Saludos!

**Comment by PabloMartinsDeMaltoz** [comment]
Buenas tardes Facundo , antes que nada te agradesco por la rewiev ! ya realice los cambios para que el texto quede mejor con respecto al wievport . Nose si me termina de convencer , yo no le pondria una foto mia pero buen xD jajaj . Quedo a la espera de tus comentarios.

Saludos y gracias nuevamente

**Comment by FacundoEG** [comment]
Pablo ahi lo revise y te quedo espectacular! muy bueno ese texto quedo super responsive. Tambien las partes de portfolio y servicios donde contienen los templates quedaron mucho mejor! 

De mi parte te cierro este issue porque se resolvio todo!

Te mando un saludo y exitos en el proximo modulo!
